### ISSUE TITLE
Error syncing with 4am collection

### ISSUE THREAD

**Issue by frankmilliron** [malfunct/SyncCollection#5]
Seems the Total Replay zip file is very large and times out the download. Is there a way to filter the sync based on size? Or skip an individual file?

**Comment by malfunct** [comment]
There is not a way to filter by size. You could force the file to be skipped by manually editing fileList.txt to include an entry for the file.

For instance: TotalReplay 1/1/2030 3:00:46 AM

remember it is a tab character between the name and the date. I picked 2030 so that you don't have to worry about the file being updated to a newer time and wanting to be downloaded.
________________________________

**Comment by frankmilliron** [comment]
That's great. Your solution seems to work. I keep an ancient imac running windows alive just to use this software to sync 4am and wozaday collections, so thank you!
